# The alias rule creates another name a rule can be referred to as. 
# You can set an alias for your build setting target path to make it easier to read on the command line.

# We create alias for the platform to get a easier to read command line instead of having to use bare metal name as is.
# Create alias depending on the requirement of the board to be used and the compiler. Sample alias creation is as follows.


# Alias for Main application with IAR Compiler.
alias(
    name = "Main_application",
    actual = "//platforms:stm32f407VG_iar",
    visibility = ["//visibility:public"]
)

# Alias for Main application with GCC Compiler.
# alias(
#     name = "Main_application",
#     actual = "//platforms:stm32u585oi_gcc",
#     visibility = ["//visibility:public"]
# )

# Alias for Main application with IAR Compiler.
# alias(
#     name = "Main_application",
#     actual = "//platforms:stm32u585oi_iar",
#     visibility = ["//visibility:public"]
# )

# Alias for Main application with GCC Compiler.
# alias(
#     name = "Main_application",
#     actual = "//platforms:stm32l552ze_gcc",
#     visibility = ["//visibility:public"]
# )

# Alias for PDS application with GCC Compiler.
# alias(
#     name = "PDS_application",
#     actual = "//platforms:stm32l041e6_gcc",
#     visibility = ["//visibility:public"]
# )

# Alias for PDS application with IAR Compiler.
# alias(
#     name = "Main_application",
#     actual = "//platforms:stm32l041e6_iar",
#     visibility = ["//visibility:public"]
# )

# Alias for nRF application with GCC Compiler.
# alias(
#     name = "nRF_application",
#     actual = "//platforms:nRF52840_xxAA_gcc",
#     visibility = ["//visibility:public"]
# )

# Alias for nRF application with IAR Compiler.
# alias(
#     name = "nRF_application",
#     actual = "//platforms:nRF52840_xxAA_iar",
#     visibility = ["//visibility:public"]
# )
