# The alias rule creates another name a rule can be referred to as. 
# You can set an alias for your build setting target path to make it easier to read on the command line.

# We create alias for the platform to get a easier to read command line instead of having to use bare metal name as is.
# Create alias depending on the requirement of the board to be used and the compiler. Sample alias creation is as follows.


# Alias for Main application with IAR Compiler.
alias(
    name = "Main_application",
    actual = "//platforms:stm32f407VG_iar",
    visibility = ["//visibility:public"]
)


